### ISSUE TITLE
Is it possible to start this application behind reverse proxy at the specific path?

### ISSUE THREAD

**Issue by ezh** [pottava/docker-webui#5]
I have nginx frontend that publish few internal infrastructure backends under specific locations.
```
i.e. jenkins -> /jenkins
     pormeteus -> /prometeus
     and so on
```

I want to publish ```docker-webui``` under ```/docker-webui``` location. Very original, isn`t it?

For such behaviour docker-webui must use only relative paths or have special option that allow to set prefix. I didn't find any notes about prefix option within code. Is docker-webui support relative path behaviour?

**Comment by pottava** [comment]
@ezh Thanks for your great request. It'll be very helpful :) I'm sorry for my late response.

**Comment by pottava** [comment]
You can use `APP_PATH_PREFIX` to specify the path prefix. Have a good day!
